name: Grace and Truth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3325460874475539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010e42'
    - '#e8a8a9'
    - '#5b73af'
    - '#762c45'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
